# Generated by Django 5.2 on 2026-10-02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactEnquiry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("enquiry_type", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=5000)),
                ("status", models.CharField(choices=[("new", "New"), ("in_progress", "In progress"), ("closed", "Closed")], default="new", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="contactenquiry",
            index=models.Index(fields=["status", "created_at"], name="common_cont_status_b95bd1_idx"),
        ),
    ]
