# Generated by Django 5.2 on 2026-10-02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_contactenquiry"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contactenquiry",
            new_name="common_cont_status_ee230e_idx",
            old_name="common_cont_status_b95bd1_idx",
        ),
    ]
