# Generated by Django 5.2 on 2026-10-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_rename_common_cont_status_b95bd1_idx_common_cont_status_ee230e_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactenquiry",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
