# Generated by Django 5.2.17 on 2026-10-07 20:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_contactenquiry_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailyVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('visitor_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='common_anal_date_6ce554_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'visitor_hash'), name='unique_analytics_daily_visitor')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('path', models.CharField(max_length=255)),
                ('referrer_host', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(default='other', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['date'], name='common_anal_date_0bf49d_idx'), models.Index(fields=['date', 'path'], name='common_anal_date_01e130_idx'), models.Index(fields=['date', 'referrer_host'], name='common_anal_date_87a231_idx')],
            },
        ),
    ]
