# Generated by Django 5.2.17 on 2026-10-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_analyticsdailyvisitor_analyticspageview'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('history', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
    ]
