# Generated by Django 5.2.17 on 2026-10-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='section',
            field=models.CharField(choices=[('hero', 'Hero'), ('membership', 'Membership'), ('training', 'Training'), ('knowledge', 'Knowledge'), ('news', 'News'), ('events', 'Events'), ('services', 'Services'), ('partners', 'Partners')], max_length=20),
        ),
    ]
