# Generated by Django 5.2.17 on 2026-10-02 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_listing_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSNavigationMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='CMSSiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(default='global', unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CMSArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('content_type', models.CharField(choices=[('news', 'News'), ('insight', 'Insight'), ('event', 'Event'), ('notice', 'Notice')], default='news', max_length=20)),
                ('author_display_name', models.CharField(blank=True, max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_articles_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_articles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CMSArticleRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived'), ('superseded', 'Superseded')], default='draft', max_length=12)),
                ('title', models.CharField(max_length=255)),
                ('standfirst', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.cmsarticle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_article_revisions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='cmsarticle',
            name='current_draft_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_for_articles', to='content.cmsarticlerevision'),
        ),
        migrations.AddField(
            model_name='cmsarticle',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_for_articles', to='content.cmsarticlerevision'),
        ),
        migrations.CreateModel(
            name='CMSCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taxonomy', models.CharField(choices=[('news', 'News'), ('insight', 'Insight'), ('event', 'Event'), ('document', 'Document')], default='news', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['taxonomy', 'position', 'name'],
                'constraints': [models.UniqueConstraint(fields=('taxonomy', 'slug'), name='content_cms_category_taxonomy_slug')],
            },
        ),
        migrations.AddField(
            model_name='cmsarticle',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.cmscategory'),
        ),
        migrations.AddField(
            model_name='cmsarticle',
            name='primary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_articles', to='content.cmscategory'),
        ),
        migrations.CreateModel(
            name='CMSMediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='cms/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=300)),
                ('caption', models.TextField(blank=True)),
                ('credit', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio')], default='image', max_length=12)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('archived', 'Archived')], default='ready', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_media_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cmsarticlerevision',
            name='cover_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='article_cover_revisions', to='content.cmsmediaasset'),
        ),
        migrations.CreateModel(
            name='CMSNavigationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived'), ('superseded', 'Superseded')], default='draft', max_length=12)),
                ('snapshot', models.JSONField(blank=True, default=list)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_navigation_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.cmsnavigationmenu')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='cmsnavigationmenu',
            name='current_draft_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_for_menus', to='content.cmsnavigationrevision'),
        ),
        migrations.AddField(
            model_name='cmsnavigationmenu',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_for_menus', to='content.cmsnavigationrevision'),
        ),
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=150)),
                ('template_key', models.CharField(default='standard', max_length=80)),
                ('is_system_page', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_pages_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label', 'path'],
            },
        ),
        migrations.CreateModel(
            name='CMSNavigationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=120)),
                ('link_type', models.CharField(choices=[('page', 'Page'), ('internal', 'Internal path'), ('external', 'External URL')], default='internal', max_length=12)),
                ('href', models.CharField(blank=True, max_length=1000)),
                ('open_in_new_tab', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.cmsnavigationitem')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.cmsnavigationrevision')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='content.cmspage')),
            ],
            options={
                'ordering': ['position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='CMSPageRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived'), ('superseded', 'Superseded')], default='draft', max_length=12)),
                ('eyebrow', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
                ('canonical_path', models.CharField(blank=True, max_length=255)),
                ('robots', models.CharField(default='index,follow', max_length=80)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('review_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_page_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.cmspage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page_social_revisions', to='content.cmsmediaasset')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='cmspage',
            name='current_draft_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_for_pages', to='content.cmspagerevision'),
        ),
        migrations.AddField(
            model_name='cmspage',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_for_pages', to='content.cmspagerevision'),
        ),
        migrations.CreateModel(
            name='CMSPageSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot', models.CharField(default='main', max_length=80)),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich text'), ('callout', 'Callout'), ('stat_grid', 'Statistics'), ('card_grid', 'Card grid'), ('feature_list', 'Feature list'), ('quote', 'Quote'), ('image', 'Image'), ('image_with_copy', 'Image with copy'), ('document_list', 'Document list'), ('article_feed', 'Article feed'), ('event_feed', 'Event feed'), ('cta_banner', 'CTA banner'), ('member_directory', 'Member directory'), ('contact_details', 'Contact details')], max_length=40)),
                ('position', models.PositiveIntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('primary_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='page_sections', to='content.cmsmediaasset')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.cmspagerevision')),
            ],
            options={
                'ordering': ['slot', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CMSSiteSettingsRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived'), ('superseded', 'Superseded')], default='draft', max_length=12)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cms_site_settings_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.cmssitesettings')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='cmssitesettings',
            name='current_draft_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_for_settings', to='content.cmssitesettingsrevision'),
        ),
        migrations.AddField(
            model_name='cmssitesettings',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_for_settings', to='content.cmssitesettingsrevision'),
        ),
        migrations.AddConstraint(
            model_name='cmsarticlerevision',
            constraint=models.UniqueConstraint(fields=('article', 'number'), name='content_cms_article_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='cmsnavigationrevision',
            constraint=models.UniqueConstraint(fields=('menu', 'number'), name='content_cms_navigation_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='cmspagerevision',
            constraint=models.UniqueConstraint(fields=('page', 'number'), name='content_cms_page_revision_number'),
        ),
        migrations.AddConstraint(
            model_name='cmspagesection',
            constraint=models.UniqueConstraint(fields=('revision', 'slot', 'position'), name='content_cms_section_position'),
        ),
        migrations.AddConstraint(
            model_name='cmssitesettingsrevision',
            constraint=models.UniqueConstraint(fields=('settings', 'number'), name='content_cms_settings_revision_number'),
        ),
    ]
