# Generated by Django 5.2.17 on 2026-10-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_cmsnavigationmenu_cmssitesettings_cmsarticle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmspagesection',
            name='section_type',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('faq', 'FAQ'), ('hero', 'Hero'), ('rich_text', 'Rich text'), ('callout', 'Callout'), ('stat_grid', 'Statistics'), ('card_grid', 'Card grid'), ('feature_list', 'Feature list'), ('quote', 'Quote'), ('image', 'Image'), ('image_with_copy', 'Image with copy'), ('document_list', 'Document list'), ('article_feed', 'Article feed'), ('event_feed', 'Event feed'), ('cta_banner', 'CTA banner'), ('member_directory', 'Member directory'), ('contact_details', 'Contact details')], max_length=40),
        ),
    ]
