# Generated by Django 5.2.17 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_directory_hero_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmspagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("gallery", "Gallery"), ("faq", "FAQ"), ("hero", "Hero"), ("rich_text", "Rich text"),
                    ("callout", "Callout"), ("stat_grid", "Statistics"), ("card_grid", "Card grid"),
                    ("feature_list", "Feature list"), ("quote", "Quote"), ("image", "Image"),
                    ("image_with_copy", "Image with copy"), ("document_list", "Document list"),
                    ("article_feed", "Article feed"), ("event_feed", "Event feed"), ("cta_banner", "CTA banner"),
                    ("member_directory", "Member directory"), ("contact_details", "Contact details"), ("partner_logos", "Partner logos"),
                ],
                max_length=40,
            ),
        ),
    ]
