# Generated by Django 5.2.17 on 2026-10-02 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_seed_membership_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipapplication',
            name='requested_type',
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='application_kind',
            field=models.CharField(choices=[('new_membership', 'New membership'), ('upgrade', 'Membership upgrade')], default='new_membership', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='assigned_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='membership.membershiptype'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='current_membership_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='cv',
            field=models.FileField(blank=True, max_length=500, upload_to='membership_applications/cv/%Y/%m/'),
        ),
    ]
