# Generated by Django 5.2 on 2026-10-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0003_remove_membershipapplication_requested_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipapplication",
            name="recommending_agent",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
