# Generated by Django 5.2.17 on 2026-10-02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("membership", "0004_membershipapplication_recommending_agent")]

    operations = [
        migrations.CreateModel(
            name="MemberDirectoryEntry",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=255)),
                ("designation", models.CharField(choices=[("HFIoD", "Honorary Fellow"), ("FIoD", "Fellow"), ("MIoD", "Member"), ("AIoD", "Associate")], max_length=10)),
                ("as_of_date", models.DateField()),
                ("is_published", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["designation", "sort_order", "full_name"]},
        ),
        migrations.AddIndex(model_name="memberdirectoryentry", index=models.Index(fields=["is_published", "designation", "full_name"], name="membership__is_publ_432feb_idx")),
    ]
